services:
  node00:
    image: ${DOCKER_TAG}
    container_name: ${NODE00_NAME}
    environment:
      - PORT=${NODE00_PORT}
    ports:
      - ${NODE00_PORT}:${NODE00_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "test -f /tmp/pilot-server.log" ]
      interval: 5s
      timeout: 3s
      retries: 5
  node01:
    image: ${DOCKER_TAG}
    container_name: ${NODE01_NAME}
    environment:
      - PORT=${NODE01_PORT}
    ports:
      - ${NODE01_PORT}:${NODE01_PORT}
      # depends_on:
      #   node00:
      #     condition: service_healthy
  node02:
    image: ${DOCKER_TAG}
    container_name: ${NODE02_NAME}
    environment:
      - PORT=${NODE02_PORT}
    ports:
      - ${NODE02_PORT}:${NODE02_PORT}
      # depends_on:
      #   node00:
      #     condition: service_healthy

networks:
  pilot-net:
    driver: bridge
    ipam:
      driver: default
