// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.6
// source: proto00.proto

package proto00

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Linker_Info_FullMethodName      = "/Linker/Info"
	Linker_Subscribe_FullMethodName = "/Linker/Subscribe"
)

// LinkerClient is the client API for Linker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkerClient interface {
	Info(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoRes, error)
	Subscribe(ctx context.Context, in *SubscribeReq, opts ...grpc.CallOption) (Linker_SubscribeClient, error)
}

type linkerClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkerClient(cc grpc.ClientConnInterface) LinkerClient {
	return &linkerClient{cc}
}

func (c *linkerClient) Info(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoRes)
	err := c.cc.Invoke(ctx, Linker_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkerClient) Subscribe(ctx context.Context, in *SubscribeReq, opts ...grpc.CallOption) (Linker_SubscribeClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Linker_ServiceDesc.Streams[0], Linker_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &linkerSubscribeClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Linker_SubscribeClient interface {
	Recv() (*Heartbeat, error)
	grpc.ClientStream
}

type linkerSubscribeClient struct {
	grpc.ClientStream
}

func (x *linkerSubscribeClient) Recv() (*Heartbeat, error) {
	m := new(Heartbeat)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LinkerServer is the server API for Linker service.
// All implementations must embed UnimplementedLinkerServer
// for forward compatibility
type LinkerServer interface {
	Info(context.Context, *InfoReq) (*InfoRes, error)
	Subscribe(*SubscribeReq, Linker_SubscribeServer) error
	mustEmbedUnimplementedLinkerServer()
}

// UnimplementedLinkerServer must be embedded to have forward compatible implementations.
type UnimplementedLinkerServer struct {
}

func (UnimplementedLinkerServer) Info(context.Context, *InfoReq) (*InfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedLinkerServer) Subscribe(*SubscribeReq, Linker_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedLinkerServer) mustEmbedUnimplementedLinkerServer() {}

// UnsafeLinkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkerServer will
// result in compilation errors.
type UnsafeLinkerServer interface {
	mustEmbedUnimplementedLinkerServer()
}

func RegisterLinkerServer(s grpc.ServiceRegistrar, srv LinkerServer) {
	s.RegisterService(&Linker_ServiceDesc, srv)
}

func _Linker_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkerServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Linker_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkerServer).Info(ctx, req.(*InfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Linker_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LinkerServer).Subscribe(m, &linkerSubscribeServer{ServerStream: stream})
}

type Linker_SubscribeServer interface {
	Send(*Heartbeat) error
	grpc.ServerStream
}

type linkerSubscribeServer struct {
	grpc.ServerStream
}

func (x *linkerSubscribeServer) Send(m *Heartbeat) error {
	return x.ServerStream.SendMsg(m)
}

// Linker_ServiceDesc is the grpc.ServiceDesc for Linker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Linker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Linker",
	HandlerType: (*LinkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Linker_Info_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Linker_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto00.proto",
}
